//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Coopemep.IBAN.TFOExterno {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IPELTFOExternoSoap", Namespace="http://pel.com/webservices/TFO/IPELTFOExterno")]
    public partial class IPELTFOExterno : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ServicioDisponibleOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerInformacionCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IPELTFOExterno() {
            this.Url = global::Coopemep.IBAN.Properties.Settings.Default.Coopemep_IBAN_TFOExterno_TransferenciaTercerosClient;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ServicioDisponibleCompletedEventHandler ServicioDisponibleCompleted;
        
        /// <remarks/>
        public event ObtenerInformacionCuentaCompletedEventHandler ObtenerInformacionCuentaCompleted;
        
        /// <remarks/>
        public event EnviarCompletedEventHandler EnviarCompleted;
        
        /// <remarks/>
        public event ConsultarCompletedEventHandler ConsultarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pel.com/webservices/TFO/IPELTFOExterno/ServicioDisponible", RequestNamespace="http://pel.com/webservices/TFO/IPELTFOExterno", ResponseNamespace="http://pel.com/webservices/TFO/IPELTFOExterno", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ServicioDisponible() {
            object[] results = this.Invoke("ServicioDisponible", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ServicioDisponibleAsync() {
            this.ServicioDisponibleAsync(null);
        }
        
        /// <remarks/>
        public void ServicioDisponibleAsync(object userState) {
            if ((this.ServicioDisponibleOperationCompleted == null)) {
                this.ServicioDisponibleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServicioDisponibleOperationCompleted);
            }
            this.InvokeAsync("ServicioDisponible", new object[0], this.ServicioDisponibleOperationCompleted, userState);
        }
        
        private void OnServicioDisponibleOperationCompleted(object arg) {
            if ((this.ServicioDisponibleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServicioDisponibleCompleted(this, new ServicioDisponibleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pel.com/webservices/TFO/IPELTFOExterno/ObtenerInformacionCuenta", RequestNamespace="http://pel.com/webservices/TFO/IPELTFOExterno", ResponseNamespace="http://pel.com/webservices/TFO/IPELTFOExterno", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InformacionCuenta ObtenerInformacionCuenta(string cuentaCliente, string idcliente) {
            object[] results = this.Invoke("ObtenerInformacionCuenta", new object[] {
                        cuentaCliente,
                        idcliente});
            return ((InformacionCuenta)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerInformacionCuentaAsync(string cuentaCliente, string idcliente) {
            this.ObtenerInformacionCuentaAsync(cuentaCliente, idcliente, null);
        }
        
        /// <remarks/>
        public void ObtenerInformacionCuentaAsync(string cuentaCliente, string idcliente, object userState) {
            if ((this.ObtenerInformacionCuentaOperationCompleted == null)) {
                this.ObtenerInformacionCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerInformacionCuentaOperationCompleted);
            }
            this.InvokeAsync("ObtenerInformacionCuenta", new object[] {
                        cuentaCliente,
                        idcliente}, this.ObtenerInformacionCuentaOperationCompleted, userState);
        }
        
        private void OnObtenerInformacionCuentaOperationCompleted(object arg) {
            if ((this.ObtenerInformacionCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerInformacionCuentaCompleted(this, new ObtenerInformacionCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pel.com/webservices/TFO/IPELTFOExterno/Enviar", RequestNamespace="http://pel.com/webservices/TFO/IPELTFOExterno", ResponseNamespace="http://pel.com/webservices/TFO/IPELTFOExterno", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta Enviar(Transferencia transferencia) {
            object[] results = this.Invoke("Enviar", new object[] {
                        transferencia});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarAsync(Transferencia transferencia) {
            this.EnviarAsync(transferencia, null);
        }
        
        /// <remarks/>
        public void EnviarAsync(Transferencia transferencia, object userState) {
            if ((this.EnviarOperationCompleted == null)) {
                this.EnviarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarOperationCompleted);
            }
            this.InvokeAsync("Enviar", new object[] {
                        transferencia}, this.EnviarOperationCompleted, userState);
        }
        
        private void OnEnviarOperationCompleted(object arg) {
            if ((this.EnviarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarCompleted(this, new EnviarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://pel.com/webservices/TFO/IPELTFOExterno/Consultar", RequestNamespace="http://pel.com/webservices/TFO/IPELTFOExterno", ResponseNamespace="http://pel.com/webservices/TFO/IPELTFOExterno", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransferenciaEnviada Consultar(string codReferencia) {
            object[] results = this.Invoke("Consultar", new object[] {
                        codReferencia});
            return ((TransferenciaEnviada)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarAsync(string codReferencia) {
            this.ConsultarAsync(codReferencia, null);
        }
        
        /// <remarks/>
        public void ConsultarAsync(string codReferencia, object userState) {
            if ((this.ConsultarOperationCompleted == null)) {
                this.ConsultarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarOperationCompleted);
            }
            this.InvokeAsync("Consultar", new object[] {
                        codReferencia}, this.ConsultarOperationCompleted, userState);
        }
        
        private void OnConsultarOperationCompleted(object arg) {
            if ((this.ConsultarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCompleted(this, new ConsultarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pel.com/webservices/TFO/IPELTFOExterno")]
    public partial class InformacionCuenta {
        
        private Moneda codMonedaField;
        
        private string nomClienteField;
        
        private short codMotivoRechazoField;
        
        /// <remarks/>
        public Moneda CodMoneda {
            get {
                return this.codMonedaField;
            }
            set {
                this.codMonedaField = value;
            }
        }
        
        /// <remarks/>
        public string NomCliente {
            get {
                return this.nomClienteField;
            }
            set {
                this.nomClienteField = value;
            }
        }
        
        /// <remarks/>
        public short CodMotivoRechazo {
            get {
                return this.codMotivoRechazoField;
            }
            set {
                this.codMotivoRechazoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pel.com/webservices/TFO/IPELTFOExterno")]
    public enum Moneda {
        
        /// <remarks/>
        Colones = 1,
        
        /// <remarks/>
        Dolares = 2,
        
        /// <remarks/>
        Euros = 4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pel.com/webservices/TFO/IPELTFOExterno")]
    public partial class Respuesta {
        
        private EstadoOperacion codEstadoField;
        
        private short codMotivoRechazoField;
        
        /// <remarks/>
        public EstadoOperacion CodEstado {
            get {
                return this.codEstadoField;
            }
            set {
                this.codEstadoField = value;
            }
        }
        
        /// <remarks/>
        public short CodMotivoRechazo {
            get {
                return this.codMotivoRechazoField;
            }
            set {
                this.codMotivoRechazoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pel.com/webservices/TFO/IPELTFOExterno")]
    public enum EstadoOperacion {
        
        /// <remarks/>
        NoExiste = 1,
        
        /// <remarks/>
        Rechazada = 2,
        
        /// <remarks/>
        Autorizada = 4,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransferenciaEnviada))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pel.com/webservices/TFO/IPELTFOExterno")]
    public partial class Transferencia {
        
        private short codEntidadOrigenField;
        
        private string cuentaSinpeOrigenField;
        
        private short codMotivoField;
        
        private Moneda codMonedaField;
        
        private string cuentaClienteField;
        
        private decimal montoField;
        
        private string iDOrigenField;
        
        private string nomOrigenField;
        
        private string servicioField;
        
        private string iDDestinoField;
        
        private string codReferenciaField;
        
        private string descripcionField;
        
        /// <remarks/>
        public short CodEntidadOrigen {
            get {
                return this.codEntidadOrigenField;
            }
            set {
                this.codEntidadOrigenField = value;
            }
        }
        
        /// <remarks/>
        public string CuentaSinpeOrigen {
            get {
                return this.cuentaSinpeOrigenField;
            }
            set {
                this.cuentaSinpeOrigenField = value;
            }
        }
        
        /// <remarks/>
        public short CodMotivo {
            get {
                return this.codMotivoField;
            }
            set {
                this.codMotivoField = value;
            }
        }
        
        /// <remarks/>
        public Moneda CodMoneda {
            get {
                return this.codMonedaField;
            }
            set {
                this.codMonedaField = value;
            }
        }
        
        /// <remarks/>
        public string CuentaCliente {
            get {
                return this.cuentaClienteField;
            }
            set {
                this.cuentaClienteField = value;
            }
        }
        
        /// <remarks/>
        public decimal Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string IDOrigen {
            get {
                return this.iDOrigenField;
            }
            set {
                this.iDOrigenField = value;
            }
        }
        
        /// <remarks/>
        public string NomOrigen {
            get {
                return this.nomOrigenField;
            }
            set {
                this.nomOrigenField = value;
            }
        }
        
        /// <remarks/>
        public string Servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
        
        /// <remarks/>
        public string IDDestino {
            get {
                return this.iDDestinoField;
            }
            set {
                this.iDDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string CodReferencia {
            get {
                return this.codReferenciaField;
            }
            set {
                this.codReferenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pel.com/webservices/TFO/IPELTFOExterno")]
    public partial class TransferenciaEnviada : Transferencia {
        
        private short codEntidadDestinoField;
        
        private EstadoOperacion codEstadoField;
        
        private short codMotivoRechazoField;
        
        private System.DateTime fecEnvioField;
        
        /// <remarks/>
        public short CodEntidadDestino {
            get {
                return this.codEntidadDestinoField;
            }
            set {
                this.codEntidadDestinoField = value;
            }
        }
        
        /// <remarks/>
        public EstadoOperacion CodEstado {
            get {
                return this.codEstadoField;
            }
            set {
                this.codEstadoField = value;
            }
        }
        
        /// <remarks/>
        public short CodMotivoRechazo {
            get {
                return this.codMotivoRechazoField;
            }
            set {
                this.codMotivoRechazoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FecEnvio {
            get {
                return this.fecEnvioField;
            }
            set {
                this.fecEnvioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ServicioDisponibleCompletedEventHandler(object sender, ServicioDisponibleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServicioDisponibleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServicioDisponibleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ObtenerInformacionCuentaCompletedEventHandler(object sender, ObtenerInformacionCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerInformacionCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerInformacionCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InformacionCuenta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InformacionCuenta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void EnviarCompletedEventHandler(object sender, EnviarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConsultarCompletedEventHandler(object sender, ConsultarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransferenciaEnviada Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransferenciaEnviada)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591